# Generated by Django 2.1.5 on 2019-04-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0002_request_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='location',
            new_name='from_location',
        ),
        migrations.AddField(
            model_name='request',
            name='to_location',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
    ]
